### ISSUE TITLE
写js模板字符串时，不能自动补全

### ISSUE THREAD

**Issue by zedhugh** [manateelazycat/awesome-pair#11]
在写 js/jsx 或 ts/tsx 代码时，在模板字符串中，没法自动补全右括号

如果能在模板字符串里补全就很贴心了

**Comment by manateelazycat** [comment]
你说的是哪种括号?

**Comment by zedhugh** [comment]
花括号，这样的 
```
`${}`
```
这种情况就需要补全后面的括号，但是现在不会补全，

而且在下面这个位置时， `"` 和 `[` 应该也需要补全
```
`${|}`
```

我现在想到的一个比较简单的办法就是在特定的 `mode`
中，在字符串中也开启补全就可以了

**Comment by manateelazycat** [comment]
开启是比较简单的, 但是要先想一想会不会出现副作用.

因为很多JS框架的字符串有很多意思, 如果默认开启补全, 可能会导致某些情况下, 开启后还要手动删除, 那样就更烦了.

这个先想一想吧, 默认没开启字符串里面括号补全除了各种JS框架的兼容性问题, 还有一个重要的原因就是字符串里面没法做括号匹配的语义, 一旦错了, 删除都是要靠手删除, 很烦.

**Comment by zedhugh** [comment]
那能不能在字符串里面，默认不补全的时候用 `self-insert-command`这个命令替换`insert`呢？

这样的话，awesome-pair不处理补全，让另外的插件处理补全

比如我是开启了`electric-pair-mode`的，用这个作为awesome-pair的一个补充也是挺好的，这样也就可以解决我上面说的问题了

**Comment by manateelazycat** [comment]
> 那能不能在字符串里面，默认不补全的时候用 `self-insert-command`这个命令替换`insert`呢？
> 
> 这样的话，awesome-pair不处理补全，让另外的插件处理补全
> 
> 比如我是开启了`electric-pair-mode`的，用这个作为awesome-pair的一个补充也是挺好的，这样也就可以解决我上面说的问题了

我先写个补丁吧, 我不建议你混用两种插件, 那样问题更多.

**Comment by manateelazycat** [comment]
Done https://github.com/manateelazycat/awesome-pair/commit/b03660cbf1b512a5357368fa26ef648607a4dcd1
