### ISSUE TITLE
consistent behavior when killing html attribute

### ISSUE THREAD

**Issue by JJPandari** [manateelazycat/awesome-pair#12]
(`|` means the cursor/point)

When executing paredit or awesome-pair's kill command in most of the codes, some codes after point get deleted:

```
int a| = 1;
```

==`awesome-pair-kill`==>

```
int a
```

However, when killing an html attribute, the whole attribute gets killed:

```
<input name="a" type="text" valu|e="123"/>
```

==`awesome-pair-kill`==>

```
<input name="a" type="text" />
```

This feels really surprising to me. I expect the following behavior (**because that's what paredit normally do: delete what's after point**):

```
<input name="a" type="text" valu|e="123"/>
```

==`awesome-pair-kill`==>

```
<input name="a" type="text" valu/>
```

---

My suggestion is:
1. change `awesome-pair-kill` to kill only what's after point on html attribute
2. add another kill function, say, `awesome-pair-kill-whole`, to kill both what's before and after point (but only the region of current semantic unit, of course)

**Comment by manateelazycat** [comment]
I used to be a fan of paredit, I don't think the way paredit is the right behavior.
Thank you for your suggestion. I suggest that you get used to it.
After getting used to it, you will feel that awesome-pair.el will be better.

**Comment by manateelazycat** [comment]
其实 paredit 更多的是一种习惯， awesome-pair-kill 为认为你在属性区域直接删除后面的属性，因为像 paredit 那样只删除后面的字符串，你会花费更多的时间去编辑属性。

你先习惯一下，说不定你会认同我上面说的细微差别呢？

@JJPandari
