### ISSUE TITLE
`awesome-pair-kill` can kill more than one line?

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-pair#16]
Seems `awesome-pair-kill` only cares about the syntax, but not actual lines. When inside a multiline string, or before a multiline sexp (lisp expression or balances expression in other languages, such as python function), it kills until the end of the string or sexp. I think the delete range should not pass current line (since it replaces the original `kill-line` command anyway). Is this by design or misbehavior?

**Comment by manateelazycat** [comment]
就是这样设计的，不是为了替换 kill-line 命令的。

**Comment by manateelazycat** [comment]
awesome-pair 的很多行为非常像 paredit 的习惯，只是在很多细节上做的更完善而已。

**Comment by AmaiKinono** [comment]
事实上我没有用过 paredit，所以感觉这个命令并不是很直观。仔细想一下的话，删掉整个表达式也合理（毕竟不这么做的话等于啥也没删），但

- 现在这个命令的 docstring 说了一些和 paredit 有关的事，没有说命令本身是做什么的。是不是应该改一下？
- 我认为在多行字符串中删到本行结尾是更合理的，我想这样修改它，您是否接受？

**Comment by manateelazycat** [comment]
这个命令就是和 paredit 保持一致的行为，删除所有字符串非常方便，你可以增加新的命令，但是我不想修改这个命令现在的行为，这是我多年的习惯。

因为插件首先是要给我自己用的，然后再看别人的需求，如果我自己都不开心了，我可能不会接受这种的补丁，抱歉。

**Comment by AmaiKinono** [comment]
嗯理解 :D 其实这里我自己再包装个命令也很简单
