### ISSUE TITLE
awesome-pair-kill doesn't respect tags in web-mode

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-pair#17]
Take a simple example:

``` html
<p>some|thing</p>
```

`|` stands for the cursor. when calling `awesome-pair-kill`, it works like the normal `kill-line`.

I've tried to play with the code, it actually goes into the last condition branch of `awesome-pair-web-mode-kill`, and run `awesome-pair-kill-sexps-on-line`. I don't know if this is right, but Emacs doesn't deal with sexps very well in non-lisp languages, see https://github.com/fxbois/web-mode/issues/1078 and [forward-sexp goes to eol in python mode (but only sometimes)](https://emacs.stackexchange.com/questions/12234/forward-sexp-goes-to-eol-in-python-mode-but-only-sometimes). I feel there should be a condition to capture this situation, rather than fall to the last one.

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/awesome-pair/commit/6d64096e049402d105494fe81e91a0a9512c18a6

**Comment by AmaiKinono** [comment]
Thanks!
