### ISSUE TITLE
`awesome-pair-space` inteferes with eldoc display.

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-pair#18]
With vanilla Emacs, eldoc shows whenever we are in a function's arglist:

![vanilla](https://user-images.githubusercontent.com/28714352/63207618-c838ca00-c0fb-11e9-8202-b391b394ba94.gif)

But when bound `SPC` to `awesome-pair-space`, the display disappears when the point is after a space:

![awesome-pair](https://user-images.githubusercontent.com/28714352/63207628-e7375c00-c0fb-11e9-8f00-0dbd07cfe467.gif)

This can be reproduced using `emacs -Q`:

``` emacs-lisp
(add-to-list 'load-path "~/.emacs.d/straight/repos/awesome-pair/")
(require 'awesome-pair)
(awesome-pair-mode)

(define-key awesome-pair-mode-map (kbd "SPC") 'awesome-pair-space)
```

**Comment by manateelazycat** [comment]
我旅游完回去看吧，可能要到月底了，如果你知道原因，欢迎提交PR ;)

**Comment by AmaiKinono** [comment]
我已经查到原因了。eldoc 里面有一个 eldoc-message-commands 变量，如果执行了这里面的命令，eldoc 就会刷新显示。默认的情况下里面是一些插入、移动、窗口一类的命令，我们应当把 awesome-pair 的输入和移动类命令都加进去。

趁此机会发现我的 evil 已经把这个变量塞满了。。。（它是个长度为 31 的 vector），我会在 readme 中加入关于这一点的说明。

*Update:* 惊奇地发现，虽然 eldoc-message-commands 已经满了，但是再通过 `eldoc-add-command` 加入命令却一点儿问题也没有。甚至我在 `evil` 之前把 awesome-pair 的命令加进去，再让 evil 把它们刷没都可以工作，which is just so weird。总之，就先假设 eldoc 其实有某种能保证工作的机制吧。。。

**Comment by manateelazycat** [comment]
我测试了一下非常完美，牛逼牛逼！ ;)
