### ISSUE TITLE
insert-translated-name-current-parse-state has no definition

### ISSUE THREAD

**Issue by LuoPX-15510486969** [manateelazycat/awesome-pair#2]
after successful installed awesome-pair, when i press "(" it shows the following message:
Symbol’s function definition is void: insert-translated-name-current-parse-state
when i  M-x to call function directly it shows the message too

**Comment by LuoPX-15510486969** [comment]
i find it's defintion in insert-translated-name.el
so awesome-pair depends on insert-translated-name.el

**Comment by manateelazycat** [comment]
No, I just copy code from insert-translated-name.el and forgot rename.

Has fixed by https://github.com/manateelazycat/awesome-pair/commit/b8140be70f909a4e74da3f4d8046b8a4c2c51fd2
