### ISSUE TITLE
awesome-pair-kill kills backward when before closing tag in web-mode

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-pair#20]
Before:

```
some text <p>something|</p>
```

`|` stands for cursor. After `awesome-pair-kill`, it becomes

```
some text |</p>
```

I think it really shouldn't do anything in this case.

**Comment by manateelazycat** [comment]
Fixed by https://github.com/manateelazycat/awesome-pair/commit/9a8329733357500e3fbb2dd46b79e85f3c6adf6c
