### ISSUE TITLE
Scan error: "Unbalanced parentheses" when wrapping top level things.

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-pair#23]
In emacs-lisp-mode, call `awesome-pair-wrap-round` here:

``` emacs-lisp-mode
|(a sexp here)
```

It wraps successfully, but signals an error: `Scan error: "Unbalanced parentheses" when wrapping top level things, 16, 1`

If move the cursor in that sexp, it shows `Indenting region...done`.

This is caused by `awesome-pair-indent-parenthesis-area`. This functions runs after wrapping, and it calls `backward-up-list` and `up-list`, which would definitely cause problem when cursor is at top level.

I'm not sure how to fix this problem. A simple `ignore-errors` will do the thing, but it would be better if `awsome-pair-indent-parenthesis-area` can actually decide the region to indent at this case.

**Comment by AmaiKinono** [comment]
上面这个例子，包裹双引号或大括号时还是有这个问题

**Comment by manateelazycat** [comment]
> 上面这个例子，包裹双引号或大括号时还是有这个问题

单独提Issue吧。
