### ISSUE TITLE
Thoughts on extensibility?

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-pair#24]
我记得你讲过 `awesome-pair` 是为了适应所有编程语言而设计的，但现在的架构我认为对开发者和用户而言都不太容易扩展。如果你愿意考虑一个可扩展的架构的话，我有一些初步的想法：

- 提供一组状态函数，通过它们能获取到光标现在是在字符串/注释/代码中，往后往前在哪能找到定界符，定界符有多长，等等。

  这组函数的行为用户可以改变，比如说它先读取一个列表，从里面查找现在的模式下应该用哪个函数，没有的话再走默认逻辑，用户可以改动这个列表。默认逻辑只管括号和双引号。

  这组函数所返回的状态不应是简单的 `非空`/`nil`，应该是一个标识符。由默认逻辑返回的标识符可以是 `'default`，用户注入的逻辑可以返回自定义的标识符。

- 将所有的交互式命令全部建立在上述状态函数的基础上，不再临时计算所需的信息。当读到非默认的标识符时，逻辑由用户指定（同样可以通过一个列表）。

- 给上述两层函数各自提供一些工具函数，以简化其编写。

例：实现 go-mode 中被 `...` 包裹的字符串中，按 `"` 不插入 `\"`：

- 用户给 `go-mode` 下的 `awesome-pair-in-string-p` 注入逻辑，使得遇到这种情况时返回 `'triple-dot`。

- 用户给 `go-mode` 下的 `awesome-pair-double-quote` 注入逻辑，使得接收到 `'triple-dot` 时插入 `"`

- 其余交互式函数，若在 `go-mode` 下调用 `awesome-pair-in-string-p`，接收到 `'triple-dot` 标识符，由于用户没有指定逻辑，仍然按接收到 `'default` 处理。

**Comment by manateelazycat** [comment]
你那样做，会被框架本身得复杂性而拖累，最后变得反而没法扩展。

因为很多语言本身相互就会冲突，统一框架只是理想状态，最简单和清晰的实现就是现在这种，虽然看着很复杂，但是代码其实很清晰 

一旦你引入这些工具函数，未来的路会越来越窄，因为很多开发者用了这些灵活的接口写私有代码，最后你改也不是，不改也不是。

go-mode可以就像webo-mode那样做特有分支处理。

谢谢你的建议，但是我不太喜欢这个方案，过于理想化了

**Comment by manateelazycat** [comment]
真正的智能括号代码逻辑很复杂，不是一堆状态函数可以组合的，而且不同编程语言之间冲突很大，还会有新的编程语言出来，新的语法

代码的清晰永远比规划型的架构设计更灵活和健壮，特别是面对未知领域的时候
