### ISSUE TITLE
How should we design delete-char and kill-word commands?

### ISSUE THREAD

**Issue by AmaiKinono** [manateelazycat/awesome-pair#25]
It's easy for them to respect delimiters like (), [] and {}, but does it worth to support complex delimiters?

Take an example:

```
<p>|</p>
```

After backward-delete, it should look like this?

```
<p|</p>
```

or this?

```
<p|></p>
```

After backward-kill-word, it should look like this?

```
<|</p>
```

or this?

```
|
```

My thought is it's good enough for only `awesome-pair-kill` and `awesome-pair-backward-kill` to respect them. But these often goes too far, we need some commands like `awesome-pair-mark-sexp` and `awesome-pair-kill-sexp`, and maybe we can base `awesome-pair-(backward)-kill` on it.

Since I am not familiar with html, I will use some LaTeX code as example:

```
$ something \langle ... \rangle some other things $
            ^
```

After `awesome-pair-kill`, I'll have this:

```
$ something $
            ^
```

But sometimes I want this (i.e. remove the `\langle ... \rangle` part), and there's no easy way to do it:

```
$ something some other things $
            ^
```

To summarize it, here's my proposal:

- Have operations on things smaller than a sexp (like kill a char or a word) respect (), [] and {}, but not complex pairs.

- Have operations on a sexp, or things bigger than a sexp (like `awesome-pair-kill`) respect complex pairs.

- Add commands to kill a sexp backward/forward, and we can base `awesome-pair-kill` and `awesome-pair-backward-kill` on it, so we only need to handle the complexity in these "single sexp" commands.

**Comment by manateelazycat** [comment]
HTML 模板这样做不行的，因为你一旦删除了Tag内容，HTML语法就不会平衡了，一旦语法失去平衡就没法正常编辑了，这也是 instant-rename-tag 为什么用 overlay mark 而不是直接编辑tag来实现。

如果要删除tag，请直接用 awesome-pair-unwrap

awesome-pair 没有啥设计，更多是根据实际遇到的问题去做贴心的交互行为改进。

**Comment by manateelazycat** [comment]
HTML的attribute或者tag包裹的内容可以用 awesome-pair 去编辑。

但是Tag的编辑，最好用 web-mode 和 sgml-mode 的插件去处理，我不建议 awesome-pair 去重复一份 web-mode 的代码。

**Comment by AmaiKinono** [comment]
> HTML 模板这样做不行的，因为你一旦删除了Tag内容，HTML语法就不会平衡了

现在的 backward/forward-delete 就是可以一直删进 tag 里边去的。

> 如果要删除tag，请直接用 awesome-pair-unwrap

> Tag的编辑，最好用 web-mode 和 sgml-mode 的插件去处理

我不是建议用删除字符或单词的命令来编辑 tag，只是如果做了这两个命令，总得考虑它们在 tag 旁边的行为应该怎样，不然将来有可能产生行为不统一的问题。我还是用 LaTeX 举例，如果将来针对 LaTeX 做了扩展，那么 LaTeX 的 tag 经常有长这样的：

```
\begin{equation}
...
\end{equation}
```

因为 tag 后边是花括号，所以删除的时候是会跳进里边的。但是 html 的 tag 两边是尖括号，删除的时候就直接干掉了。

另外后面还有个增加「kill 单个 sexp」的提案，你怎么看？

**Comment by manateelazycat** [comment]
> > HTML 模板这样做不行的，因为你一旦删除了Tag内容，HTML语法就不会平衡了
> 
> 现在的 backward/forward-delete 就是可以一直删进 tag 里边去的。
> 
> > 如果要删除tag，请直接用 awesome-pair-unwrap
> 
> > Tag的编辑，最好用 web-mode 和 sgml-mode 的插件去处理
> 
> 我不是建议用删除字符或单词的命令来编辑 tag，只是如果做了这两个命令，总得考虑它们在 tag 旁边的行为应该怎样，不然将来有可能产生行为不统一的问题。我还是用 LaTeX 举例，如果将来针对 LaTeX 做了扩展，那么 LaTeX 的 tag 经常有长这样的：
> 
> ```
> \begin{equation}
> ...
> \end{equation}
> ```
> 
> 因为 tag 后边是花括号，所以删除的时候是会跳进里边的。但是 html 的 tag 两边是尖括号，删除的时候就直接干掉了。
> 
> 另外后面还有个增加「kill 单个 sexp」的提案，你怎么看？

我的建议：
awesome-pair 是为了方便而创建的，每种语言都有自己的特殊语法，所以不应该强行的统一到底是进入括号删除还是直接删除Tag，而是在目标语言的环境中，删除应该怎么做 “才自然” ？只要是符合直觉的都是好的设计，但是有时候好用的插件并不一定要先符合我们的 “统一逻辑” 再去做实现，那只是满足了内在的逻辑统一，但有时候往往不好用。

我不是不赞同内在逻辑统一，而是希望根据实际场景，先用 mode 判断做一个分支，直觉好用 > 内在逻辑统一

关于 Kill sexp 的想法，只有在Lisp语言中，按照 Sexp 块来编辑才是好用的，其他编程语言对 sexp 的支持不一定好。ParEdit原来针对Sexp有很多支持，但是最后都太复杂了，记不住， awesome-pair 都实现不了。

BTW，建议以后，补丁和Issue都针对一件事情讨论，这样好讨论和合并补丁。

**Comment by manateelazycat** [comment]
如果要支持LaTex，我建议直接先做一个 LaTex 的代码分支出来，先看看怎么做，可以做到LaTex操作最优，不要担心重复代码。

我的编程经验是，先满足需求，等有重复代码再重构，往往为了最简洁的，最低重复代码，会构建一堆更加复杂难懂的框架代码出来，最后别的贡献者看不懂，就更难贡献代码了。

Issue先关闭，建议按照实际场景发PR ;)
