### ISSUE TITLE
希望加强对SAS的支持

### ISSUE THREAD

**Issue by a5corpii** [manateelazycat/awesome-pair#31]
SAS是[Statistical Analysis Software/System](https://www.sas.com/en_us/software/stat.html)用的语言，主要是金融、医药等领域做统计分析和数据处理。

目前在Emacs中最常用的package是[ESS](http://ess.r-project.org/)，同时ESS也支持[R](https://cran.r-project.org/)、julia的补全、高亮等功能……

因为这几个更偏data science一点，尤其是SAS使用场景更为单一，故在Emacs中写SAS的需求可能跟其他程序语言有所不同，亦没有[texlab](https://texlab.netlify.app/)、[ccls](https://github.com/MaskRay/ccls)这样的辅助工具。再加上诞生时间久远，语法“灵活”，简单粗暴地将awesome-pair拿来就用、并不完美。

目前已知的问题有：
1. SAS以`/* comment */`的形式注释，`awesome-pair-kill`只能删除注释外的空格，对注释的操作无反应；
2. SAS以`;`作为一句程序结尾，在删除某个参数的时候，往往连分号一起被删掉，个人希望保留，尤其是当其位于关键字的后边时；
3. 接上条，使用`awesome-pair-wrap-round`的时候，如果括号中包含了原来就在行尾的`;`，希望能自动调出括号，保持语法正确。

这是一个简单的例子：
``` SAS
/* 生成列表备用 */
data ec;
    set raw.ec;
    ecdatim=put(ECDAT, $10.) || '' || put(ECTIM, $8.);
    ecdatinn=input(ecdatim, nldatm20.);
    keep subject ecdat ectim ecdatim ecdatinn;
    label ecdatim='日期时间';
run;
proc sort data=ec;
    by subject;
run;
```

**Comment by manateelazycat** [comment]
很抱歉，我并不用SAS，我现在可能没有时间对这个东西进行支持。
