### ISSUE TITLE
写C++的时候输入 { 后想让其自动换行

### ISSUE THREAD

**Issue by kurt-steiner** [manateelazycat/awesome-pair#36]
语文不好，看视频吧  

https://user-images.githubusercontent.com/46296608/135284672-b0ae0e70-7296-4b65-b6d8-9ea8765e594e.mp4

话说这些补全插件都是为写lisp设计的吗？不知道能不能像其他IDE那样补全花括号

**Comment by manateelazycat** [comment]
目前是没有自动换行，自动换行函数也好写啊。

awesome-pair 是为所有语言设计的，没有针对Lisp, 难道不能补全花括号？

**Comment by kurt-steiner** [comment]
https://user-images.githubusercontent.com/46296608/135304387-1093058c-fd33-4818-9637-7417332d58de.mp4

这是我开了`electric-pair-mode`后的效果

**Comment by manateelazycat** [comment]
最新版更新后，把快捷键 RET 绑定到 awesome-pair-newline 命令上。

**Comment by kurt-steiner** [comment]
谢谢大佬

**Comment by kurt-steiner** [comment]
还有一件事，写代码的时候发现体验不怎么好，我记得这种缩进不对齐的问题上次我用的时候就有了  

https://user-images.githubusercontent.com/46296608/135625887-a5f41954-ceb3-4e51-a98b-e2f9d473af04.mp4

**Comment by manateelazycat** [comment]
> 还有一件事，写代码的时候发现体验不怎么好，我记得这种缩进不对齐的问题上次我用的时候就有了
> 
>  2021-10-01.21-14-00.mp4

那是你没有加对应mode，比如web-mode，空白模式肯定不知道你的编程语言是啥，emacs怎么能正确缩进？

**Comment by kurt-steiner** [comment]
你说的是切换major mode 吗，你看看右下角 :yum:

**Comment by manateelazycat** [comment]
> 还有一件事，写代码的时候发现体验不怎么好，我记得这种缩进不对齐的问题上次我用的时候就有了
> 
>  2021-10-01.21-14-00.mp4

修复了

**Comment by kurt-steiner** [comment]
https://user-images.githubusercontent.com/46296608/136702071-44669760-50b1-402a-ba9b-e7be8b40b47e.mp4

还是有点问题，不能回车了 另外能不能放出你的系统下 `awesome-pair` 的运行演示，我怕是我这里配置有问题

**Comment by manateelazycat** [comment]
我这边没问题，你自己用 emacs -Q 自己排查一下配置吧。

**Comment by kurt-steiner** [comment]
https://user-images.githubusercontent.com/46296608/136725358-545f826a-5676-47c1-9820-f1b2d781ec6a.mp4

我这还有个小建议，回车之后光标会跳到行首，能不能让他跳到下一行对齐

**Comment by manateelazycat** [comment]
>  2021-10-11.10-34-06.mp4 
> 我这还有个小建议，回车之后光标会跳到行首，能不能让他跳到下一行对齐

这不是一个好主意，第一不是所有语言都有正确的缩进的（比如Python和Haskell），错误缩进反而给用户带来麻烦，第二像C语言的宏定义按照Emacs风格都是顶格来缩进的，awesome-pair 没法预测下一行写啥。

建议把智能缩进绑定到Tab键，要缩进的时候按一下Tab按键就行了。

**Comment by manateelazycat** [comment]
>  2021-10-11.10-34-06.mp4 
> 我这还有个小建议，回车之后光标会跳到行首，能不能让他跳到下一行对齐

我平常的习惯是，把 C-l 和 C-o 绑定到 open-newline.el 两个函数上，但是依然保留 C-m 只做简单的换行。

**Comment by manateelazycat** [comment]
>  2021-10-11.10-34-06.mp4 
> 我这还有个小建议，回车之后光标会跳到行首，能不能让他跳到下一行对齐

尝试一下最新版，我以前没有自动加入空行的时候主要用 open-newline 插件，现在自动插入空行的时候，发现是要自动对齐一下才方便。

**Comment by kurt-steiner** [comment]
要不再修下 `web-mode` ，没有自动换行诶
