### ISSUE TITLE
awesome-pair-wrap-round

### ISSUE THREAD

**Issue by guodongsoft** [manateelazycat/awesome-pair#4]
#Rust language#
>awesome-pair-wrap-round before:
```rust
fn main() {
    (test)
}
```

>awesome-pair-wrap-round after:
```rust
fn main() {
          test
         }
```

>want
```rust
fn main() {
    test
}
```

**Comment by manateelazycat** [comment]
I believe you want fix command 'awesome-pair-unwrap'.

Has fixed by https://github.com/manateelazycat/awesome-pair/commit/fa03531816b5157789db552e26fde680a04d0cdb
