### ISSUE TITLE
写shell时，不能直接输入右括号

### ISSUE THREAD

**Issue by guodongsoft** [manateelazycat/awesome-pair#9]
写shell时，有下面的写法
``` shell
case x in 
     abc)
     ...
     ;;
     xyz)
     ...
     ;;
     *)
     echo "...."
easc
```
但现在，没法直接先输入右括号，一输入就直接跳走了。只能先输入左括号，出现`()`后，再把左括号去掉

**Comment by manateelazycat** [comment]
https://github.com/manateelazycat/awesome-pair/commit/29901e7848e21f35f9f3bd4fa3a320f9f52ecfc2
已经修复了

如果还有问题请提新的issue
